apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: custom-domain-issuer
  namespace: custom-domain-ingressroutes
spec:
  acme:
    email: admin@01cloud.com
    privateKeySecretRef:
      name: custom-domain-letsencrypt-production
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: zerone

---

{{ if eq .Values.dns.provider "aws" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@{{ template "baseDomain" . }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        route53:
          region: us-east-2
          accessKeyID: {{ .Values.aws.awsAccessKey }}
          secretAccessKeySecretRef:
            key: secretKey
            name: route53-secret-key
{{- end }}

---
{{ if eq .Values.dns.provider "gcp" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: admin@{{ template "baseDomain" . }}
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: {{ .Values.gcp.gcloudProject }}
          serviceAccountSecretRef:
            name: cloud-dns-cred
            key: cloud-dns.json
{{- end }}

---

{{ if eq .Values.dns.provider "cloudflare" }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    email: admin@{{ template "baseDomain" . }}
    privateKeySecretRef:  
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.cloudflare.email }}
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
{{- end }}