{{ if eq .Values.dns.provider "aws" }}
apiVersion: v1
data:
  secretKey: {{ .Values.aws.awsSecretKey | b64enc }}
kind: Secret
metadata:
  name: route53-secret-key
  namespace: default
{{- end }}

---

{{ if eq .Values.dns.provider "gcp" }}
apiVersion: v1
data:
  cloud-dns.json: {{ .Values.gcp.googleAppCred }}
kind: Secret
metadata:
  name: cloud-dns-cred 
  namespace: default
{{- end }}

---

{{ if eq .Values.dns.provider "cloudflare" }}
apiVersion: v1
data:
  api-key: {{ .Values.cloudflare.apiKey | b64enc }}
kind: Secret
metadata:
  name: cloudflare-api-key-secret
type: Opaque  
{{- end}}